// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnfmxlucomulnxcprhzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZm14bHVjb211bG54Y3ByaHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjk0ODEsImV4cCI6MjA3MTg0NTQ4MX0.yHIqni532eVUr6-2aF6BHRvTA0DF-UaYn5dPm3EkuNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});